In [1]:
import numpy as np
import cvxpy as cp

In [2]:
x1 = cp.Variable(nonneg=True)
x2 = cp.Variable(nonneg=True)
x3 = cp.Variable(nonneg=True)
x4 = cp.Variable(nonneg=True)
s1 = cp.Variable(nonneg=True)
s2 = cp.Variable(nonneg=True)
s3 = cp.Variable(nonneg=True)

objective = cp.Minimize(-2*x2 - x3 + 7*x4)

constraints = [-x1 - x2 + x3 + x4 + s1 == 5,
               -2*x1 + x2 - 2*x4 + s2 == 3,
               x2 - 2*x3 + s3 == 12,
               -2*x2 - x3 + 7*x4 == -100]

problem = cp.Problem(objective, constraints)
problem.solve(solver=cp.GUROBI)
print(f"Status: {problem.status}")
print(f"Optimal value: {problem.value:.2f}")
print(f"x* = ({x1.value:.2f}, {x2.value:.2f}, {x3.value:.2f}, {x4.value:.2f}, {s1.value:.2f}, {s2.value:.2f}, {s3.value:.2f})")


Set parameter Username
Academic license - for non-commercial use only - expires 2025-10-28
Status: optimal
Optimal value: -100.00
x* = (19.70, 42.40, 15.20, 0.00, 51.90, 0.00, 0.00)


In [3]:
def minor(A, i, j):
    return np.delete(np.delete(A, i, axis=0), j, axis=1)

def adjoint(A):
    n = A.shape[0]
    return np.array([[(-1)**(i+j) * np.linalg.det(minor(A, j, i)) for j in range(n)] for i in range(n)])

def inverse(A):
    return adjoint(A) / np.linalg.det(A)

def three_inverse(A):
    adj = np.zeros((3, 3))
    a = A[0, 0]
    b = A[0, 1]
    c = A[0, 2]
    d = A[1, 0]
    e = A[1, 1]
    f = A[1, 2]
    g = A[2, 0]
    h = A[2, 1]
    i = A[2, 2]
    adj[0, 0] = e*i - f*h
    adj[0, 1] = -(b*i - c*h)
    adj[0, 2] = b*f - c*e
    adj[1, 0] = -(d*i - f*g)
    adj[1, 1] = a*i - c*g
    adj[1, 2] = -(a*f - c*d)
    adj[2, 0] = d*h - e*g
    adj[2, 1] = -(a*h - b*g)
    adj[2, 2] = a*e - b*d
    det = a*(e*i - f*h) - b*(d*i - f*g) + c*(d*h - e*g)
    inv = adj / det
    return np.round(inv, 2)


In [4]:
A = np.array([[1, 2, 2],
              [0, 1, 1],
              [0, 3, 1]])
A_inv = three_inverse(A)

print(A_inv)
print(np.round(np.linalg.inv(A), 2))




[[ 1.  -2.  -0. ]
 [-0.  -0.5  0.5]
 [-0.   1.5 -0.5]]
[[ 1.  -2.  -0. ]
 [ 0.  -0.5  0.5]
 [ 0.   1.5 -0.5]]


In [5]:
A_inv2 = inverse(A)
print(A_inv2)

[[ 1.  -2.  -0. ]
 [ 0.  -0.5  0.5]
 [-0.   1.5 -0.5]]


In [6]:
B = np.array([[1, 2],
              [3, 4]])
B_inv = inverse(B)
print(B_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [10]:
C = np.array([[1, 2, 1],
              [0, 1, 3],
              [0, 3, 4]])
C_inv = three_inverse(C)
print(C_inv)

[[ 1.   1.  -1. ]
 [-0.  -0.8  0.6]
 [-0.   0.6 -0.2]]


In [14]:
avg = (95*3.5 + 100*3 + 90*3.5 + 93*2 + 96*2 + 94*3 + 98*3)/20
avg

95.075